---
- name: Install and configuare Jetty9 web server
  hosts: localhost
  connection: local
  become: true
  become_method: sudo
  tasks:
   - name: apt-get updating repositories update_cache
     apt:
      update_cache: yes
      
   - name: Install Jetty9
     apt:
      state: present
      
   - name: start Jetty9 service
     systemd:
      name: jetty9
      state: started
      
   - name: Check url response of tomcat on server1
     uri:
      url: http://localhost:8080
      status_code: 200
      
   - name: Check url response of tomcat on server2
     uri:
      url: http://localhost:8080
