---
- name : Ubuntu catalog update
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt: 
        update_cache: yes
        upgrade: 'yes' 
...