---
- name: "Install and Configure Tomcat9 Web server"
  become: yes
  become_method: sudo
  hosts: ubuntu
  tasks:
    - name: Install JDK11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add tomcat group
      group:
        name: tomcat

    - name: Add tomcat user
      user:
        name: tomcat
        group: tomcat
        home: /user/share/tomcat
        createhome: no

    - name: create /opt/tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        mode: 0775

    - name: Download & Unarchive
      unarchive:
        src: http://apache.cs.utah.edu/tomcat/tomcat-9/v9.0.68/bin/apache-tomcat-9.0.68.tar.gz
        dest: /opt/tomcat
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Change ownership
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Copy Tomcat service from local to remote
      copy:
        src: tomcat.service
        dest: /etc/systemd/system/
        mode: 0775

    - name: Start and enable Tomcat service
      systemd:
        name: tomcat
        state: started
        enabled: true
        daemon_reload: true
...