---
- name : Ubuntu catalog update
  hosts: localhost
  connection: local
  become: yes
  tasks:   
    - name: Update apt-get repo and cache
      apt:
        update_cache: yes
        upgrade: yes
